[workspace]
members = [
    "crates/*",
    "packages/hwpx-python",
]
resolver = "2"

[workspace.package]
version = "0.2.1"
edition = "2021"
authors = ["kevin <ftkevin12@gmail.com>"]
license = "MIT"

[workspace.dependencies]

[profile.release]
lto = "fat"
strip = true
codegen-units = 1
opt-level = 3
panic = "unwind"
