[package]
name = "hwp-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
hwp-core = { path = "../crates/hwp-core" }
libfuzzer-sys = "0.4"

[[bin]]
name = "parse_auto"
path = "fuzz_targets/parse_auto.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_hwpx"
path = "fuzz_targets/parse_hwpx.rs"
test = false
doc = false
bench = false
