#!/usr/bin/env python3
"""Tests for check_release_versions.py."""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).with_name("check_release_versions.py")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def make_repo(root: Path, version: str = "0.2.0") -> None:
    write(
        root / "Cargo.toml",
        f"""
[workspace]
members = ["crates/*", "packages/hwpx-python"]

[workspace.package]
version = "{version}"
edition = "2021"
license = "MIT"
""".lstrip(),
    )
    write(
        root / "Cargo.lock",
        f"""
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "hwp-core"
version = "{version}"

[[package]]
name = "hwpx-python"
version = "{version}"
""".lstrip(),
    )
    write(
        root / "crates/hwp-core/Cargo.toml",
        """
[package]
name = "hwp-core"
version.workspace = true
edition.workspace = true
""".lstrip(),
    )
    write(
        root / "packages/hwpx-python/Cargo.toml",
        f"""
[package]
name = "hwpx-python"
version = "{version}"
edition = "2021"
""".lstrip(),
    )
    write(
        root / "packages/hwpx-python/pyproject.toml",
        f"""
[project]
name = "hwpx"
version = "{version}"
""".lstrip(),
    )
    write(
        root / "packages/hwpx-python/python/hwpx/__init__.py",
        f'__version__ = "{version}"\n',
    )


class CheckReleaseVersionsTest(unittest.TestCase):
    def run_checker(self, root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), "--root", str(root)],
            text=True,
            capture_output=True,
            check=False,
        )

    def test_accepts_synchronized_versions(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            make_repo(root)

            result = self.run_checker(root)

            self.assertEqual(result.returncode, 0, result.stderr)

    def test_rejects_python_init_version_drift(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            make_repo(root)
            write(root / "packages/hwpx-python/python/hwpx/__init__.py", '__version__ = "0.2.1"\n')

            result = self.run_checker(root)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("packages/hwpx-python/python/hwpx/__init__.py", result.stderr)
            self.assertIn("0.2.1", result.stderr)
            self.assertIn("0.2.0", result.stderr)

    def test_rejects_cargo_lock_workspace_package_drift(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            make_repo(root)
            write(
                root / "Cargo.lock",
                """
version = 4

[[package]]
name = "hwp-core"
version = "0.2.0"

[[package]]
name = "hwpx-python"
version = "0.1.0"
""".lstrip(),
            )

            result = self.run_checker(root)

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Cargo.lock package hwpx-python", result.stderr)
            self.assertIn("0.1.0", result.stderr)
            self.assertIn("0.2.0", result.stderr)


if __name__ == "__main__":
    unittest.main()
